### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yezz123** [EvanBacon/firebase-instagram#18]
after installing expo and restart my laptop i use expo start  and this is the resultat :

Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
(node:28748) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@57.9.26\src\Project.ts:1854:16)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

**Comment by Thinkeraty** [comment]
I am getting the same error!!
Someone please help us!

**Comment by Fredysv** [comment]
Same error! pls help
I saw some error when running `yarn`, maybe thats where the issue comes but idk

**Comment by sohumsen** [comment]
maybe try this https://stackoverflow.com/questions/58120990/how-to-resolve-the-error-on-react-native-start
