### ISSUE TITLE
yarn run ios or yarn start not working

### ISSUE THREAD

**Issue by impactcolor** [EvanBacon/firebase-instagram#4]
Thanks for doing this great article and code.  I was trying to run it and got an error 
yarn run ios says error Comamand ios not found
yarn start gives error
npm start also.

Can you let me know if I'm missing something?

**Comment by antzshrek** [comment]
@impactcolor What error messages do you get?

**Comment by impactcolor** [comment]
@antzshrek This is the error: yarn run v1.7.0
error Command "ios" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
I get this when I run yarn run ios.  

When I run yarn start I get this:
yarn run v1.7.0
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by EvanBacon** [comment]
This is an expo project. You start it with `exp start` learn more here: https://docs.expo.io/versions/latest/workflow/exp-cli
